name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Step 1 - Code Checkout
        uses: actions/checkout@v3

      - name: Step 2 - Set up Python ${{ matrix.python-version }}
        run: |
          python -m venv venv_${{ matrix.python-version }}
          source venv_${{ matrix.python-version }}/bin/activate
          python -m pip install --upgrade pip

      - name: Step 3 - Display Python Version
        run: |
          source venv_${{ matrix.python-version }}/bin/activate
          python -c "import sys; print(sys.version)"

      - name: Step 4 - Create Artifact
        run: |
          echo ${{ matrix.python-version }} > python-version.txt
          echo "::set-output name=version::$(cat python-version.txt)"
        id : python-version
        
      - name: Step 5 - Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Python Versions Artifact
          path: python-version.txt

